# Generated by Django 5.1.3 on 2024-11-15 16:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('icone_URL', models.URLField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('magico', 'Mágico'), ('fisico', 'Físico')], max_length=50)),
                ('quantidade_especializacoes', models.IntegerField()),
                ('link', models.URLField()),
                ('ativo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('icone_URL', models.URLField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('raca', models.CharField(choices=[('humano', 'Humano'), ('elfo', 'Elfo'), ('anao', 'Anão'), ('qunari', 'Qunari')], max_length=50)),
                ('idade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'personagens',
            },
        ),
        migrations.CreateModel(
            name='ReferenciasPersonagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DA_Fansite.classe')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DA_Fansite.personagem')),
            ],
            options={
                'verbose_name': 'referencia do personagem',
                'verbose_name_plural': 'referencias dos personagens',
            },
        ),
    ]
